/*
Q.2) Create a table Employees12 (Employee_Id,Name,Badge_number,Hire_date). The
Employee_Id should be generated by the sequence which starts from 1 with
increment of 1 in an ascending order, and Badge_number should also be generated
by other sequence which starts from 1000 with increment of 1 in ascending order.
Create procedure in PL/SQL which generates the values of the sequence and adds
the same in the table.
*/

-- Create the employees87 table
CREATE TABLE employees87 (
    employee_id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    badge_number NUMBER UNIQUE,
    hire_date DATE
);


CREATE SEQUENCE employees_seq_87
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE SEQUENCE badge_number_seq_87
START WITH 1000
INCREMENT BY 1
MINVALUE 1000
CACHE 20;
CREATE OR REPLACE PROCEDURE add_employees87 (
    p_name IN VARCHAR2,
    p_hiredate IN DATE
) IS
    v_badge_number NUMBER;  -- Variable to store the badge number
BEGIN    
    SELECT badge_number_seq_87.nextval INTO v_badge_number FROM dual;
    INSERT INTO employees87 (employee_id, name, badge_number, hire_date)
    VALUES (employees_seq_87.nextval, p_name, v_badge_number, p_hiredate);  
    COMMIT;
END;
/
BEGIN
    add_employees87('John Doe', SYSDATE);
    add_employees87('Jane Smith', SYSDATE);
END;
/
SELECT * FROM employees87;